#!bin/bash
#Coded by Suman
clear
echo -e "\033[1;93m ‎"
bash OnlineHacking/Logo.sh
sleep 5
echo -e $'\e[1;33m[\e[0m\e[1;91m Online Hacking \e[0m\e[1;33m]\e[0m\e[1;32m # Installing Dependencies ! \e[0m'
sudo apt update -y
sudo apt-get install tor -y
sudo apt install wget -y
sudo apt install php -y
sudo apt install nano
echo -e $'\e[1;33m[\e[0m\e[1;91m Online Hacking \e[0m\e[1;33m]\e[0m\e[1;32m # Enter Details to display on the Webpage \e[0m'
echo ""
#Enter Full Name
search="%nfame"
read -p "Enter Your Full Name >>> " replace
if [[ $search != "" && $replace != "" ]]; then
sed -i "s/$search/$replace/gi" index.html
fi
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#Enter Nick Name
search="%criets"
read -p "Enter Your Nick Name >>> " replace
if [[ $search != "" && $replace != "" ]]; then
sed -i "s/$search/$replace/gi" index.html
fi
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#Enter Main Text
search="%Maintext"
read -p "Enter the Main Message >>> " replace
if [[ $search != "" && $replace != "" ]]; then
sed -i "s/$search/$replace/gi" index.html
fi
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#-----------------------------------------------

echo ""                                                                                                                              echo ""                                                                                                                              php="$(ps -efw | grep php | grep -v grep | awk '{print $2}')"                                                                        ngrok="$(ps -efw | grep ngrok | grep -v grep | awk '{print $2}')"
kill -9 $php > /dev/null 2>&1
kill -9 $tor > /dev/null 2>&1

echo ""
echo -e $'\e[1;33m[\e[0m\e[1;77m Online Hacking \e[0m\e[1;33m]\e[0m\e[1;32m ## Starting Php Server \e[0m'
                  php -S 127.0.0.1:80 > /dev/null 2>&1 &
                  sleep 3
echo -e "\033[1;95mPhp server is up"
echo -e "\033[1;96mYou can check your server by accessing http://127.0.0.1:80/"
#-----------------------------------------------
sleep 1
echo -e $'\e[1;33m[\e[0m\e[1;77m HostOnion \e[0m\e[1;33m]\e[0m\e[1;32m # Configuring Files ! \e[0m'
sudo rm -rf /etc/tor/torrc
sudo cp Linux/torrc /etc/tor/
sleep 5
echo -e $'\e[1;33m[\e[0m\e[1;77m Online Hacking \e[0m\e[1;33m]\e[0m\e[1;32m ## Setting up TOR \e[0m'
sudo service tor restart
sleep 20
sudo cd /var/lib/tor/hidden_service
echo ""
clear 
sudo bash $HOME/HostDarkWeb/OnlineHacking/Logo2.sh
echo ""
echo -e $'\e[1;33m[\e[0m\e[1;77m Online Hacking \e[0m\e[1;33m]\e[0m\e[1;32m # Your Onion Site is Ready !! \e[0m'
echo ""
echo -e '\e[31m[\e[32m★\e[31m]\e[32m Your Dark Web Link \e[m '
echo -e "\e[91m "
sudo cat hostname
echo -e "\e[39m "
echo ""
echo ""
echo ""
echo -e '\e[91m[\e[92m*\e[91m]\e[1;93m Pro Tip :\e[0m\e[1;36m Replace the HTML file with your own to get your webpage hosted on Deepweb !!  '
echo ""
echo -e '\e[0m\e[1;32m ## Press CTRL + C to Exit \e[0m'
echo ""
while true
do
sleep 5
done
