#!bin/bash
#Coded by Suman
echo -e " "
killall php
echo -e " "


Logo () {
white='\e[1;37m'
green='\e[0;32m'
blue='\e[1;34m'
red='\e[1;31m'
yellow='\e[1;33m'
echo ""
echo -e "\e[95m
             ██╗  ██╗ ██████╗ ███████╗████████╗
             ██║  ██║██╔═══██╗██╔════╝╚══██╔══╝
             ███████║██║   ██║███████╗   ██║   
             ██╔══██║██║   ██║╚════██║   ██║   
             ██║  ██║╚██████╔╝███████║   ██║   
             ╚═╝  ╚═╝ ╚═════╝ ╚══════╝   ╚═╝                         
\e[33m                                                              
██████   █████  ██████  ██   ██     ██     ██ ███████ ██████  
██   ██ ██   ██ ██   ██ ██  ██      ██     ██ ██      ██   ██ 
██   ██ ███████ ██████  █████       ██  █  ██ █████   ██████  
██   ██ ██   ██ ██   ██ ██  ██      ██ ███ ██ ██      ██   ██ 
██████  ██   ██ ██   ██ ██   ██      ███ ███  ███████ ██████  \e[0m\n"
echo -e "\e[95m \e[0m\n"
  echo""    
  echo -e $'\e[1;33m\e[0m\e[1;31m  ██████████\e[0m'"\e[1;37m██████████"'\e[1;33m\e[0m\e[0;32m██████████\e[0m' '\e[1;95m\e[0m\e[1;32m Host Dark Website \e[0m''\e[1;37m\e[0m\e[1;37m [v 1.2] \e[0m'                                       
  echo ""
   echo -e $'\e[1;33m\e[0m\e[1;33m  [\e[0m\e[1;32m Github : \e[36mhttps://github.com/OnlineHacKing/HostDarkWeb \e[0m\e[1;32m\e[0m\e[1;33m]\e[0m'
   echo ""
sleep 1
echo ""
echo -e "              \033[1;91m  Author   \033[1;90m:  \033[1;95mOnline HacKing \033[1;97m(SUMAN)"
echo -e "              \033[1;93m Telegram   \033[1;90m: \033[1;96m@OnlineHacking"
echo -e "              \033[1;92m  Website   \033[1;90m: \033[1;94mwww.termux.xyz"
echo -e "              \033[1;97m  Website   \033[1;90m: \033[1;93mwww.onlinehacking.org"
echo ""
echo -e " "
sleep 1                                               
}

echo -e " "
echo ""
echo -e "\e[31m[\e[32m*\e[31m]\e[33m Enter Your Web File Folder Part : \e[m "
echo -e " "
echo -e "\e[31m[\e[32m*\e[31m]\e[33m Example \e[32m/sdcard/Download/web \e[92mor \e[32m/storage/emulated/0/Download/web  \e[m "
echo " "
echo " "
read -p $'\e[31m[\e[32m*\e[31m]\e[33m cd \e[97m' token
cd $token
echo ""





